[package]
name = "cartapy"
version = "1.0.0"
edition = "2024"
description = "Easy to use document converter"
license = "MIT"
repository = "https://github.com/g-b-f/cartapy"

[lib]
name = "_rust_wrapper"
crate-type = ["cdylib"]

[dependencies]
carta = { version = "0.0.8", features = ["read-csv", "read-tsv"] }
pyo3 = "0.29.2"
