[project]
name = "cartapy"
requires-python = ">=3.9"
description = "Easy to use document converter"
readme = "README.md"
packages = ["carta"]
license = "MIT"
license-files = ["LICENSE"]

classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
keywords = ["document", "converter", "conversion", "pandoc", "carta"]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/g-b-f/cartapy"

[build-system]
requires = ["maturin>=1.11,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=5.0.0",
    "pytest-mock>=3.14.1",
]

[tool.mypy]
check_untyped_defs = true
follow_untyped_imports = true

[tool.maturin]
include = ["carta/*"] 

[tool.ruff.lint]
extend-select = [
    "BLE",  # Blind exceptions
    "FBT",  # Boolean trap
    "A",    # Builtin shadowing
    "C4",   # Comprehensions
    "LOG",  # Logging
    "G",    # Logging formatting
    "PT",   # Pytest
    "SIM",  # Simplifications
    "TID",  # Tidy imports
    "I",    # isort
    "C901", # flake8-c901 complexity
]
[tool.pytest.ini_options]
pythonpath = ["."]
filterwarnings = ["error"]